#!/bin/bash

# Parse the environment variables and auto-create the default.vcl file
/parse

# Start varnish and log
varnishd -f /etc/varnish/default.vcl -s malloc,100M -a 0.0.0.0:${VARNISH_PORT}

if [ "${VARNISH_LOGGING}" = "ncsa" ]; then
    varnishncsa "${VARNISH_LOG_OPTIONS}"
else
    varnishlog "${VARNISH_LOG_OPTIONS}"
fi
